### PR TITLE
fix(k8s): update to SocialGouv/gitlab-ci-yml v17

### LINKED ISSUE #379: Error: secret "api-env" not found
Une petite erreur sur les environnments Hors-prod de ds-aggregator.

Events
Error: secret "api-env" not found
Source: kubelet aks-system0-15248395-vmss0001hx
Count: 24437
Sub-object: spec.initContainers{knex-migrate}
Last seen: 2020-09-28T11:43:45Z
Container image "registry.gitlab.factory.social.gouv.fr/socialgouv/ds-aggregator/api:0adfbfd7677afedd010ead4761f4967a36906d4c" already present on machine
Source: kubelet aks-system0-15248395-vmss0001hx
Count: 24168
Sub-object: spec.initContainers{knex-migrate}
Last seen: 2020-09-28T11:48:50Z

### PR DESCRIPTION
**Pull request by douglasduteil**
---

Closes #379

### CODE REVIEW

**Comment by revolunet** [comment]
should be renamed `api.configmap.yaml` and `api.sealed-secret.yaml`

**Comment by douglasduteil** [comment]
Why ? We have a naming convention ?

**Comment by revolunet** [comment]
oops i missed the "manifests" folder . previous comment dont apply

**Comment by douglasduteil** [comment]
@revolunet I think we should review the k8s code 
It seems out of sync

**Pull request merged**
